/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DnsMonitorService } from "../dnsMonitor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DnsMonitorCreateInput } from "./DnsMonitorCreateInput";
import { DnsMonitor } from "./DnsMonitor";
import { DnsMonitorFindManyArgs } from "./DnsMonitorFindManyArgs";
import { DnsMonitorWhereUniqueInput } from "./DnsMonitorWhereUniqueInput";
import { DnsMonitorUpdateInput } from "./DnsMonitorUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DnsMonitorControllerBase {
  constructor(
    protected readonly service: DnsMonitorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DnsMonitor })
  @nestAccessControl.UseRoles({
    resource: "DnsMonitor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDnsMonitor(
    @common.Body() data: DnsMonitorCreateInput
  ): Promise<DnsMonitor> {
    return await this.service.createDnsMonitor({
      data: data,
      select: {
        createdAt: true,
        domain: true,
        id: true,
        lastChecked: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DnsMonitor] })
  @ApiNestedQuery(DnsMonitorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DnsMonitor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dnsMonitors(@common.Req() request: Request): Promise<DnsMonitor[]> {
    const args = plainToClass(DnsMonitorFindManyArgs, request.query);
    return this.service.dnsMonitors({
      ...args,
      select: {
        createdAt: true,
        domain: true,
        id: true,
        lastChecked: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DnsMonitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsMonitor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dnsMonitor(
    @common.Param() params: DnsMonitorWhereUniqueInput
  ): Promise<DnsMonitor | null> {
    const result = await this.service.dnsMonitor({
      where: params,
      select: {
        createdAt: true,
        domain: true,
        id: true,
        lastChecked: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DnsMonitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsMonitor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDnsMonitor(
    @common.Param() params: DnsMonitorWhereUniqueInput,
    @common.Body() data: DnsMonitorUpdateInput
  ): Promise<DnsMonitor | null> {
    try {
      return await this.service.updateDnsMonitor({
        where: params,
        data: data,
        select: {
          createdAt: true,
          domain: true,
          id: true,
          lastChecked: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DnsMonitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DnsMonitor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDnsMonitor(
    @common.Param() params: DnsMonitorWhereUniqueInput
  ): Promise<DnsMonitor | null> {
    try {
      return await this.service.deleteDnsMonitor({
        where: params,
        select: {
          createdAt: true,
          domain: true,
          id: true,
          lastChecked: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
