/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserLogin } from "./UserLogin";
import { UserLoginCountArgs } from "./UserLoginCountArgs";
import { UserLoginFindManyArgs } from "./UserLoginFindManyArgs";
import { UserLoginFindUniqueArgs } from "./UserLoginFindUniqueArgs";
import { CreateUserLoginArgs } from "./CreateUserLoginArgs";
import { UpdateUserLoginArgs } from "./UpdateUserLoginArgs";
import { DeleteUserLoginArgs } from "./DeleteUserLoginArgs";
import { Role } from "../../role/base/Role";
import { UserLoginService } from "../userLogin.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserLogin)
export class UserLoginResolverBase {
  constructor(
    protected readonly service: UserLoginService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "read",
    possession: "any",
  })
  async _userLoginsMeta(
    @graphql.Args() args: UserLoginCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserLogin])
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "read",
    possession: "any",
  })
  async userLogins(
    @graphql.Args() args: UserLoginFindManyArgs
  ): Promise<UserLogin[]> {
    return this.service.userLogins(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserLogin, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "read",
    possession: "own",
  })
  async userLogin(
    @graphql.Args() args: UserLoginFindUniqueArgs
  ): Promise<UserLogin | null> {
    const result = await this.service.userLogin(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserLogin)
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "create",
    possession: "any",
  })
  async createUserLogin(
    @graphql.Args() args: CreateUserLoginArgs
  ): Promise<UserLogin> {
    return await this.service.createUserLogin({
      ...args,
      data: {
        ...args.data,

        role: args.data.role
          ? {
              connect: args.data.role,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserLogin)
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "update",
    possession: "any",
  })
  async updateUserLogin(
    @graphql.Args() args: UpdateUserLoginArgs
  ): Promise<UserLogin | null> {
    try {
      return await this.service.updateUserLogin({
        ...args,
        data: {
          ...args.data,

          role: args.data.role
            ? {
                connect: args.data.role,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserLogin)
  @nestAccessControl.UseRoles({
    resource: "UserLogin",
    action: "delete",
    possession: "any",
  })
  async deleteUserLogin(
    @graphql.Args() args: DeleteUserLoginArgs
  ): Promise<UserLogin | null> {
    try {
      return await this.service.deleteUserLogin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Role, {
    nullable: true,
    name: "role",
  })
  @nestAccessControl.UseRoles({
    resource: "Role",
    action: "read",
    possession: "any",
  })
  async getRole(@graphql.Parent() parent: UserLogin): Promise<Role | null> {
    const result = await this.service.getRole(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
